package com.example.myapps;

import java.util.ArrayList;
import java.util.List;

public class ConstantsConfig {

   static public List permissionsData() {
        List<PermissionListBean> permissions = new ArrayList<PermissionListBean>();
        permissions.add(new PermissionListBean("ACCEPT_HANDOVER",0.5));
        permissions.add(new PermissionListBean("ACCESS_BACKGROUND_LOCATION",0.5));
        permissions.add(new PermissionListBean("ACCESS_COARSE_LOCATION",0.5));
        permissions.add(new PermissionListBean("ACCESS_FINE_LOCATION",0.5));
        permissions.add(new PermissionListBean("ACCESS_CHECKIN_PROPERTIES",0.75));
        permissions.add(new PermissionListBean("ACCESS_LOCATION_EXTRA_COMMANDS",0.25));
        permissions.add(new PermissionListBean("ACCESS_MEDIA_LOCATION",0.5));
        permissions.add(new PermissionListBean("ACCESS_NETWORK_STATE",0.25));
        permissions.add(new PermissionListBean("ACCESS_NOTIFICATION_POLICY",0.25));
        permissions.add(new PermissionListBean("ACCESS_WIFI_STATE",0.25));
        permissions.add(new PermissionListBean("ACCOUNT_MANAGER",0.75));
        permissions.add(new PermissionListBean("ACTIVITY_RECOGNITION",0.5));
        permissions.add(new PermissionListBean("ADD_VOICEMAIL",0.5));
        permissions.add(new PermissionListBean("ANSWER_PHONE_CALLS",0.5));
        permissions.add(new PermissionListBean("BATTERY_STATS",1));
        permissions.add(new PermissionListBean("BIND_ACCESSIBILITY_SERVICE",0.75));
        permissions.add(new PermissionListBean("BIND_APPWIDGET",0.75));
        permissions.add(new PermissionListBean("BIND_AUTOFILL_SERVICE",0.75));
        permissions.add(new PermissionListBean("BIND_CALL_REDIRECTION_SERVICE",1));
        permissions.add(new PermissionListBean("BIND_CARRIER_MESSAGING_CLIENT_SERVICE",0.75));
        permissions.add(new PermissionListBean("BIND_CARRIER_SERVICES",1));
        permissions.add(new PermissionListBean("BIND_CHOOSER_TARGET_SERVICE",0.75));
        permissions.add(new PermissionListBean("BIND_CONDITION_PROVIDER_SERVICE",0.75));
        permissions.add(new PermissionListBean("BIND_DEVICE_ADMIN",0.75));
        permissions.add(new PermissionListBean("BIND_DREAM_SERVICE",0.75));
        permissions.add(new PermissionListBean("BIND_INCALL_SERVICE",1));
        permissions.add(new PermissionListBean("BIND_INPUT_METHOD",0.75));
        permissions.add(new PermissionListBean("BIND_MIDI_DEVICE_SERVICE",0.75));
        permissions.add(new PermissionListBean("BIND_NFC_SERVICE",0.75));
        permissions.add(new PermissionListBean("BIND_NOTIFICATION_LISTENER_SERVICE",0.75));
        permissions.add(new PermissionListBean("BIND_PRINT_SERVICE",0.75));
        permissions.add(new PermissionListBean("BIND_QUICK_SETTINGS_TILE",0.75));
        permissions.add(new PermissionListBean("BIND_REMOTEVIEWS",1));
        permissions.add(new PermissionListBean("BIND_SCREENING_SERVICE",1));
        permissions.add(new PermissionListBean("BIND_TELECOM_CONNECTION_SERVICE",1));
        permissions.add(new PermissionListBean("BIND_TEXT_SERVICE",0.75));
        permissions.add(new PermissionListBean("BIND_TV_INPUT",1));
        permissions.add(new PermissionListBean("BIND_VISUAL_VOICEMAIL_SERVICE",1));
        permissions.add(new PermissionListBean("BIND_VOICE_INTERACTION",0.75));
        permissions.add(new PermissionListBean("BIND_VPN_SERVICE",0.75));
        permissions.add(new PermissionListBean("BIND_VR_LISTENER_SERVICE",0.75));
        permissions.add(new PermissionListBean("BIND_WALLPAPER",1));
        permissions.add(new PermissionListBean("BLUETOOTH",0.25));
        permissions.add(new PermissionListBean("BLUETOOTH_ADMIN",0.25));
        permissions.add(new PermissionListBean("BLUETOOTH_PRIVILEGED",1));
        permissions.add(new PermissionListBean("BODY_SENSORS",0.5));
        permissions.add(new PermissionListBean("BROADCAST_PACKAGE_REMOVED",0.75));
        permissions.add(new PermissionListBean("BROADCAST_SMS",0.75));
        permissions.add(new PermissionListBean("BROADCAST_STICKY",0.25));
        permissions.add(new PermissionListBean("BROADCAST_WAP_PUSH",0.75));
        permissions.add(new PermissionListBean("CALL_COMPANION_APP",0.25));
        permissions.add(new PermissionListBean("CALL_PHONE",0.5));
        permissions.add(new PermissionListBean("CALL_PRIVILEGED",1));
        permissions.add(new PermissionListBean("CAMERA",0.5));
        permissions.add(new PermissionListBean("CAPTURE_AUDIO_OUTPUT",0.75));
        permissions.add(new PermissionListBean("CHANGE_COMPONENT_ENABLED_STATE",0.75));
        permissions.add(new PermissionListBean("CHANGE_CONFIGURATION",1));
        permissions.add(new PermissionListBean("CHANGE_NETWORK_STATE",0.25));
        permissions.add(new PermissionListBean("CHANGE_WIFI_MULTICAST_STATE",0.25));
        permissions.add(new PermissionListBean("CHANGE_WIFI_STATE",0.25));
        permissions.add(new PermissionListBean("CLEAR_APP_CACHE",1));
        permissions.add(new PermissionListBean("CONTROL_LOCATION_UPDATES",0.75));
        permissions.add(new PermissionListBean("DELETE_CACHE_FILES",1));
        permissions.add(new PermissionListBean("DELETE_PACKAGES",0.75));
        permissions.add(new PermissionListBean("DIAGNOSTIC",0.75));
        permissions.add(new PermissionListBean("DISABLE_KEYGUARD",0.25));
        permissions.add(new PermissionListBean("DUMP",0.75));
        permissions.add(new PermissionListBean("EXPAND_STATUS_BAR",0.25));
        permissions.add(new PermissionListBean("FACTORY_TEST",0.75));
        permissions.add(new PermissionListBean("FOREGROUND_SERVICE",0.25));
        permissions.add(new PermissionListBean("GET_ACCOUNTS",0.5));
        permissions.add(new PermissionListBean("GET_ACCOUNTS_PRIVILEGED",1));
        permissions.add(new PermissionListBean("GET_PACKAGE_SIZE",0.25));
        permissions.add(new PermissionListBean("GLOBAL_SEARCH",1));
        permissions.add(new PermissionListBean("INSTALL_LOCATION_PROVIDER",0.75));
        permissions.add(new PermissionListBean("INSTALL_PACKAGES",0.75));
        permissions.add(new PermissionListBean("INSTALL_SHORTCUT",0.25));
        permissions.add(new PermissionListBean("INSTANT_APP_FOREGROUND_SERVICE",0.75));
        permissions.add(new PermissionListBean("INTERNET",0.25));
        permissions.add(new PermissionListBean("KILL_BACKGROUND_PROCESSES",0.25));
        permissions.add(new PermissionListBean("LOCATION_HARDWARE",0.75));
        permissions.add(new PermissionListBean("MANAGE_DOCUMENTS",0.75));
        permissions.add(new PermissionListBean("MANAGE_OWN_CALLS",0.25));
        permissions.add(new PermissionListBean("MASTER_CLEAR",0.75));
        permissions.add(new PermissionListBean("MEDIA_CONTENT_CONTROL",0.75));
        permissions.add(new PermissionListBean("MODIFY_AUDIO_SETTINGS",0.25));
        permissions.add(new PermissionListBean("MODIFY_PHONE_STATE",0.75));
        permissions.add(new PermissionListBean("MOUNT_FORMAT_FILESYSTEMS",0.75));
        permissions.add(new PermissionListBean("MOUNT_UNMOUNT_FILESYSTEMS",0.75));
        permissions.add(new PermissionListBean("NFC",0.25));
        permissions.add(new PermissionListBean("NFC_TRANSACTION_EVENT",0.25));
        permissions.add(new PermissionListBean("PACKAGE_USAGE_STATS",1));
        permissions.add(new PermissionListBean("READ_CALENDAR",0.5));
        permissions.add(new PermissionListBean("READ_CALL_LOG",0.5));
        permissions.add(new PermissionListBean("READ_CONTACTS",0.5));
        permissions.add(new PermissionListBean("READ_EXTERNAL_STORAGE",0.5));
        permissions.add(new PermissionListBean("READ_LOGS",0.5));
        permissions.add(new PermissionListBean("READ_PHONE_NUMBERS",0.5));
        permissions.add(new PermissionListBean("READ_PHONE_STATE",0.5));
        permissions.add(new PermissionListBean("READ_SMS",0.5));
        permissions.add(new PermissionListBean("READ_SYNC_SETTINGS",0.25));
        permissions.add(new PermissionListBean("READ_SYNC_STATS",0.25));
        permissions.add(new PermissionListBean("READ_VOICEMAIL",1));
        permissions.add(new PermissionListBean("REBOOT",1));
        permissions.add(new PermissionListBean("RECEIVE_BOOT_COMPLETED",0.25));
        permissions.add(new PermissionListBean("RECEIVE_MMS",0.5));
        permissions.add(new PermissionListBean("RECEIVE_SMS",0.5));
        permissions.add(new PermissionListBean("RECEIVE_WAP_PUSH",0.5));
        permissions.add(new PermissionListBean("RECORD_AUDIO",0.5));
        permissions.add(new PermissionListBean("REORDER_TASKS",0.25));
        permissions.add(new PermissionListBean("REQUEST_COMPANION_RUN_IN_BACKGROUND",0.25));
        permissions.add(new PermissionListBean("REQUEST_COMPANION_USE_DATA_IN_BACKGROUND",0.25));
        permissions.add(new PermissionListBean("REQUEST_DELETE_PACKAGES",0.25));
        permissions.add(new PermissionListBean("REQUEST_IGNORE_BATTERY_OPTIMIZATIONS",0.25));
        permissions.add(new PermissionListBean("REQUEST_INSTALL_PACKAGES",0.75));
        permissions.add(new PermissionListBean("REQUEST_PASSWORD_COMPLEXITY",0.25));
        permissions.add(new PermissionListBean("SEND_RESPOND_VIA_MESSAGE",0.5));
        permissions.add(new PermissionListBean("SEND_SMS",0.5));
        permissions.add(new PermissionListBean("SET_ALARM",0.25));
        permissions.add(new PermissionListBean("SET_ALWAYS_FINISH",0.75));
        permissions.add(new PermissionListBean("SET_ANIMATION_SCALE",0.75));
        permissions.add(new PermissionListBean("SET_DEBUG_APP",0.75));
        permissions.add(new PermissionListBean("SET_PROCESS_LIMIT",0.75));
        permissions.add(new PermissionListBean("SET_TIME",0.75));
        permissions.add(new PermissionListBean("SET_TIME_ZONE",0.75));
        permissions.add(new PermissionListBean("SET_WALLPAPER",0.25));
        permissions.add(new PermissionListBean("SET_WALLPAPER_HINTS",0.25));
        permissions.add(new PermissionListBean("SIGNAL_PERSISTENT_PROCESSES",0.75));
        permissions.add(new PermissionListBean("SMS_FINANCIAL_TRANSACTIONS",0.75));
        permissions.add(new PermissionListBean("START_VIEW_PERMISSION_USAGE",0.75));
        permissions.add(new PermissionListBean("STATUS_BAR",0.75));
        permissions.add(new PermissionListBean("SYSTEM_ALERT_WINDOW",0.75));
        permissions.add(new PermissionListBean("TRANSMIT_IR",0.25));
        permissions.add(new PermissionListBean("UNINSTALL_SHORTCUT",0.25));
        permissions.add(new PermissionListBean("UPDATE_DEVICE_STATS",0.75));
        permissions.add(new PermissionListBean("USE_BIOMETRIC",0.25));
        permissions.add(new PermissionListBean("USE_FINGERPRINT",0.25));
        permissions.add(new PermissionListBean("USE_FULL_SCREEN_INTENT",0.25));
        permissions.add(new PermissionListBean("USE_SIP",0.5));
        permissions.add(new PermissionListBean("VIBRATE",0.25));
        permissions.add(new PermissionListBean("WAKE_LOCK",0.25));
        permissions.add(new PermissionListBean("WRITE_APN_SETTINGS",1));
        permissions.add(new PermissionListBean("WRITE_CALENDAR",0.5));
        permissions.add(new PermissionListBean("WRITE_CALL_LOG",0.5));
        permissions.add(new PermissionListBean("WRITE_CONTACTS",0.5));
        permissions.add(new PermissionListBean("WRITE_EXTERNAL_STORAGE",0.5));
        permissions.add(new PermissionListBean("WRITE_GSERVICES",0.75));
        permissions.add(new PermissionListBean("WRITE_SECURE_SETTINGS",1));
        permissions.add(new PermissionListBean("WRITE_SETTINGS",0.75));
        permissions.add(new PermissionListBean("WRITE_SYNC_SETTINGS",0.25));
        permissions.add(new PermissionListBean("WRITE_VOICEMAIL",1));
        permissions.add(new PermissionListBean("C2D_MESSAGE",0.25));
        permissions.add(new PermissionListBean("AUTHENTICATE_ACCOUNTS",0.75));
        permissions.add(new PermissionListBean("GET_TASK",1));
        permissions.add(new PermissionListBean("GET_ACCOUNTS",0.5));
        permissions.add(new PermissionListBean("MANAGE_ACCOUNTS",0.75));
        permissions.add(new PermissionListBean("USE_CREDENTIALS",0.5));
        permissions.add(new PermissionListBean("READ_SETTINGS",0.5));
        permissions.add(new PermissionListBean("UPDATE_SHORTCUT",0.25));
        permissions.add(new PermissionListBean("UPDATE_COUNT",0.25));
        permissions.add(new PermissionListBean("UPDATE_BADGE",0.25));
        permissions.add(new PermissionListBean("BROADCAST_BADGE",0.25));
        permissions.add(new PermissionListBean("CHANGE_BADGE",0.25));
        permissions.add(new PermissionListBean("DOWNLOAD_WITHOUT_NOTIFICATION",0.5));
        permissions.add(new PermissionListBean("BIND_GET_INSTALL_REFERRER_SERVICE",0.75));
        permissions.add(new PermissionListBean("READ_GSERVICE",0.5));
        permissions.add(new PermissionListBean("PROVIDER_INSERT_BADGE",0.25));
        permissions.add(new PermissionListBean("READ_GMAIL",0.5));
        permissions.add(new PermissionListBean("AUDIO_FILE_ACCESS",0.5));
        permissions.add(new PermissionListBean("FLASHLIGHT",0.25));
        permissions.add(new PermissionListBean("READ_HISTORY_BOOKMARKS",0.5));
        permissions.add(new PermissionListBean("WRITE_HISTORY_BOOKMARKS",0.5));
        permissions.add(new PermissionListBean("READ_GSETTINGS",0.5));
        permissions.add(new PermissionListBean("WRITE_GSETTINGS",0.5));
        permissions.add(new PermissionListBean("WRITE_SMS",0.5));
        permissions.add(new PermissionListBean("CAPTURE_AUDIO_HOTWORD",0.75));
        permissions.add(new PermissionListBean("EDIT_PREFERENCES",0.75));
        permissions.add(new PermissionListBean("BADGE_COUNT_READ",0.25));
        permissions.add(new PermissionListBean("BADGE_COUNT_WRITE",0.25));
        permissions.add(new PermissionListBean("BILLING",0.25));
        permissions.add(new PermissionListBean("READ_PROFILE",0.5));
        permissions.add(new PermissionListBean("READ_USER_DICTIONARY",0.5));
        permissions.add(new PermissionListBean("WRITE_USER_DICTIONARY",0.5));

        permissions.add(new PermissionListBean("ACCEPT_HANDOVER", 0.5));
        permissions.add(new PermissionListBean("ACCESS_BACKGROUND_LOCATION", 0.5));
        permissions.add(new PermissionListBean("ACCESS_COARSE_LOCATION", 0.5));
        permissions.add(new PermissionListBean("ACCESS_FINE_LOCATION", 0.5));
        permissions.add(new PermissionListBean("ACCESS_CHECKIN_PROPERTIES", 0.0));
        permissions.add(new PermissionListBean("ACCESS_LOCATION_EXTRA_COMMANDS", 0.25));
        permissions.add(new PermissionListBean("ACCESS_MEDIA_LOCATION", 0.5));
        permissions.add(new PermissionListBean("ACCESS_NETWORK_STATE", 0.25));
        permissions.add(new PermissionListBean("ACCESS_NOTIFICATION_POLICY", 0.25));
        permissions.add(new PermissionListBean("ACCESS_WIFI_STATE", 0.25));
        permissions.add(new PermissionListBean("ACCOUNT_MANAGER", 0.0));
        permissions.add(new PermissionListBean("ACTIVITY_RECOGNITION", 0.5));
        permissions.add(new PermissionListBean("ADD_VOICEMAIL", 0.5));
        permissions.add(new PermissionListBean("ANSWER_PHONE_CALLS", 0.5));
        permissions.add(new PermissionListBean("BATTERY_STATS", 1));
        permissions.add(new PermissionListBean("BIND_ACCESSIBILITY_SERVICE", 0.75));
        permissions.add(new PermissionListBean("BIND_APPWIDGET", 0.0));
        permissions.add(new PermissionListBean("BIND_AUTOFILL_SERVICE", 0.75));
        permissions.add(new PermissionListBean("BIND_CALL_REDIRECTION_SERVICE", 1));
        permissions.add(new PermissionListBean("BIND_CARRIER_MESSAGING_CLIENT_SERVICE", 0.75));
        permissions.add(new PermissionListBean("BIND_CARRIER_SERVICES", 1));
        permissions.add(new PermissionListBean("BIND_CHOOSER_TARGET_SERVICE", 0.75));
        permissions.add(new PermissionListBean("BIND_CONDITION_PROVIDER_SERVICE", 0.75));
        permissions.add(new PermissionListBean("BIND_DEVICE_ADMIN", 0.75));
        permissions.add(new PermissionListBean("BIND_DREAM_SERVICE", 0.75));
        permissions.add(new PermissionListBean("BIND_INCALL_SERVICE", 1));
        permissions.add(new PermissionListBean("BIND_INPUT_METHOD", 0.75));
        permissions.add(new PermissionListBean("BIND_MIDI_DEVICE_SERVICE", 0.75));
        permissions.add(new PermissionListBean("BIND_NFC_SERVICE", 0.75));
        permissions.add(new PermissionListBean("BIND_NOTIFICATION_LISTENER_SERVICE", 0.75));
        permissions.add(new PermissionListBean("BIND_PRINT_SERVICE", 0.75));
        permissions.add(new PermissionListBean("BIND_QUICK_SETTINGS_TILE", 0.0));
        permissions.add(new PermissionListBean("BIND_REMOTEVIEWS", 1));
        permissions.add(new PermissionListBean("BIND_SCREENING_SERVICE", 1));
        permissions.add(new PermissionListBean("BIND_TELECOM_CONNECTION_SERVICE", 1));
        permissions.add(new PermissionListBean("BIND_TEXT_SERVICE", 0.75));
        permissions.add(new PermissionListBean("BIND_TV_INPUT", 1));
        permissions.add(new PermissionListBean("BIND_VISUAL_VOICEMAIL_SERVICE", 1));
        permissions.add(new PermissionListBean("BIND_VOICE_INTERACTION", 0.75));
        permissions.add(new PermissionListBean("BIND_VPN_SERVICE", 0.75));
        permissions.add(new PermissionListBean("BIND_VR_LISTENER_SERVICE", 0.75));
        permissions.add(new PermissionListBean("BIND_WALLPAPER", 1));
        permissions.add(new PermissionListBean("BLUETOOTH", 0.25));
        permissions.add(new PermissionListBean("BLUETOOTH_ADMIN", 0.25));
        permissions.add(new PermissionListBean("BLUETOOTH_PRIVILEGED", 0.0));
        permissions.add(new PermissionListBean("BODY_SENSORS", 0.5));
        permissions.add(new PermissionListBean("BROADCAST_PACKAGE_REMOVED", 0.0));
        permissions.add(new PermissionListBean("BROADCAST_SMS", 0.0));
        permissions.add(new PermissionListBean("BROADCAST_STICKY", 0.25));
        permissions.add(new PermissionListBean("BROADCAST_WAP_PUSH", 0.0));
        permissions.add(new PermissionListBean("CALL_COMPANION_APP", 0.25));
        permissions.add(new PermissionListBean("CALL_PHONE", 0.5));
        permissions.add(new PermissionListBean("CALL_PRIVILEGED", 0.0));
        permissions.add(new PermissionListBean("CAMERA", 0.5));
        permissions.add(new PermissionListBean("CAPTURE_AUDIO_OUTPUT", 0.0));
        permissions.add(new PermissionListBean("CHANGE_COMPONENT_ENABLED_STATE", 0.0));
        permissions.add(new PermissionListBean("CHANGE_CONFIGURATION", 1));
        permissions.add(new PermissionListBean("CHANGE_NETWORK_STATE", 0.25));
        permissions.add(new PermissionListBean("CHANGE_WIFI_MULTICAST_STATE", 0.25));
        permissions.add(new PermissionListBean("CHANGE_WIFI_STATE", 0.25));
        permissions.add(new PermissionListBean("CLEAR_APP_CACHE", 1));
        permissions.add(new PermissionListBean("CONTROL_LOCATION_UPDATES", 0.0));
        permissions.add(new PermissionListBean("DELETE_CACHE_FILES", 1));
        permissions.add(new PermissionListBean("DELETE_PACKAGES", 0.0));
        permissions.add(new PermissionListBean("DIAGNOSTIC", 0.0));
        permissions.add(new PermissionListBean("DISABLE_KEYGUARD", 0.25));
        permissions.add(new PermissionListBean("DUMP", 0.0));
        permissions.add(new PermissionListBean("EXPAND_STATUS_BAR", 0.25));
        permissions.add(new PermissionListBean("FACTORY_TEST", 0.0));
        permissions.add(new PermissionListBean("FOREGROUND_SERVICE", 0.25));
        permissions.add(new PermissionListBean("GET_ACCOUNTS", 0.5));
        permissions.add(new PermissionListBean("GET_ACCOUNTS_PRIVILEGED", 1));
        permissions.add(new PermissionListBean("GET_PACKAGE_SIZE", 0.25));
        permissions.add(new PermissionListBean("GLOBAL_SEARCH", 1));
        permissions.add(new PermissionListBean("INSTALL_LOCATION_PROVIDER", 0.0));
        permissions.add(new PermissionListBean("INSTALL_PACKAGES", 0.0));
        permissions.add(new PermissionListBean("INSTALL_SHORTCUT", 0.25));
        permissions.add(new PermissionListBean("INSTANT_APP_FOREGROUND_SERVICE", 0.75));
        permissions.add(new PermissionListBean("INTERNET", 0.25));
        permissions.add(new PermissionListBean("KILL_BACKGROUND_PROCESSES", 0.25));
        permissions.add(new PermissionListBean("LOCATION_HARDWARE", 0.0));
        permissions.add(new PermissionListBean("MANAGE_DOCUMENTS", 0.0));
        permissions.add(new PermissionListBean("MANAGE_OWN_CALLS", 0.25));
        permissions.add(new PermissionListBean("MASTER_CLEAR", 0.0));
        permissions.add(new PermissionListBean("MEDIA_CONTENT_CONTROL", 0.0));
        permissions.add(new PermissionListBean("MODIFY_AUDIO_SETTINGS", 0.25));
        permissions.add(new PermissionListBean("MODIFY_PHONE_STATE", 0.0));
        permissions.add(new PermissionListBean("MOUNT_FORMAT_FILESYSTEMS", 0.0));
        permissions.add(new PermissionListBean("MOUNT_UNMOUNT_FILESYSTEMS", 0.0));
        permissions.add(new PermissionListBean("NFC", 0.25));
        permissions.add(new PermissionListBean("NFC_TRANSACTION_EVENT", 0.25));
        permissions.add(new PermissionListBean("PACKAGE_USAGE_STATS", 1));
        permissions.add(new PermissionListBean("READ_CALENDAR", 0.5));
        permissions.add(new PermissionListBean("READ_CALL_LOG", 0.5));
        permissions.add(new PermissionListBean("READ_CONTACTS", 0.5));
        permissions.add(new PermissionListBean("READ_EXTERNAL_STORAGE", 0.5));
        permissions.add(new PermissionListBean("READ_LOGS", 0.5));
        permissions.add(new PermissionListBean("READ_PHONE_NUMBERS", 0.5));
        permissions.add(new PermissionListBean("READ_PHONE_STATE", 0.5));
        permissions.add(new PermissionListBean("READ_SMS", 0.5));
        permissions.add(new PermissionListBean("READ_SYNC_SETTINGS", 0.25));
        permissions.add(new PermissionListBean("READ_SYNC_STATS", 0.25));
        permissions.add(new PermissionListBean("READ_VOICEMAIL", 1));
        permissions.add(new PermissionListBean("REBOOT", 0.0));
        permissions.add(new PermissionListBean("RECEIVE_BOOT_COMPLETED", 0.25));
        permissions.add(new PermissionListBean("RECEIVE_MMS", 0.5));
        permissions.add(new PermissionListBean("RECEIVE_SMS", 0.5));
        permissions.add(new PermissionListBean("RECEIVE_WAP_PUSH", 0.5));
        permissions.add(new PermissionListBean("RECORD_AUDIO", 0.5));
        permissions.add(new PermissionListBean("REORDER_TASKS", 0.25));
        permissions.add(new PermissionListBean("REQUEST_COMPANION_RUN_IN_BACKGROUND", 0.25));
        permissions.add(new PermissionListBean("REQUEST_COMPANION_USE_DATA_IN_BACKGROUND", 0.25));
        permissions.add(new PermissionListBean("REQUEST_DELETE_PACKAGES", 0.25));
        permissions.add(new PermissionListBean("REQUEST_IGNORE_BATTERY_OPTIMIZATIONS", 0.25));
        permissions.add(new PermissionListBean("REQUEST_INSTALL_PACKAGES", 0.75));
        permissions.add(new PermissionListBean("REQUEST_PASSWORD_COMPLEXITY", 0.25));
        permissions.add(new PermissionListBean("SEND_RESPOND_VIA_MESSAGE", 0.5));
        permissions.add(new PermissionListBean("SEND_SMS", 0.5));
        permissions.add(new PermissionListBean("SET_ALARM", 0.25));
        permissions.add(new PermissionListBean("SET_ALWAYS_FINISH", 0.0));
        permissions.add(new PermissionListBean("SET_ANIMATION_SCALE", 0.0));
        permissions.add(new PermissionListBean("SET_DEBUG_APP", 0.0));
        permissions.add(new PermissionListBean("SET_PROCESS_LIMIT", 0.0));
        permissions.add(new PermissionListBean("SET_TIME", 0.0));
        permissions.add(new PermissionListBean("SET_TIME_ZONE", 0.0));
        permissions.add(new PermissionListBean("SET_WALLPAPER", 0.25));
        permissions.add(new PermissionListBean("SET_WALLPAPER_HINTS", 0.25));
        permissions.add(new PermissionListBean("SIGNAL_PERSISTENT_PROCESSES", 0.0));
        permissions.add(new PermissionListBean("SMS_FINANCIAL_TRANSACTIONS", 0.75));
        permissions.add(new PermissionListBean("START_VIEW_PERMISSION_USAGE", 0.75));
        permissions.add(new PermissionListBean("STATUS_BAR", 0.0));
        permissions.add(new PermissionListBean("SYSTEM_ALERT_WINDOW", 0.75));
        permissions.add(new PermissionListBean("TRANSMIT_IR", 0.25));
        permissions.add(new PermissionListBean("UNINSTALL_SHORTCUT", 0.25));
        permissions.add(new PermissionListBean("UPDATE_DEVICE_STATS", 0.0));
        permissions.add(new PermissionListBean("USE_BIOMETRIC", 0.25));
        permissions.add(new PermissionListBean("USE_FINGERPRINT", 0.25));
        permissions.add(new PermissionListBean("USE_FULL_SCREEN_INTENT", 0.25));
        permissions.add(new PermissionListBean("USE_SIP", 0.5));
        permissions.add(new PermissionListBean("VIBRATE", 0.25));
        permissions.add(new PermissionListBean("WAKE_LOCK", 0.25));
        permissions.add(new PermissionListBean("WRITE_APN_SETTINGS", 0.0));
        permissions.add(new PermissionListBean("WRITE_CALENDAR", 0.5));
        permissions.add(new PermissionListBean("WRITE_CALL_LOG", 0.5));
        permissions.add(new PermissionListBean("WRITE_CONTACTS", 0.5));
        permissions.add(new PermissionListBean("WRITE_EXTERNAL_STORAGE", 0.5));
        permissions.add(new PermissionListBean("WRITE_GSERVICES", 0.0));
        permissions.add(new PermissionListBean("WRITE_SECURE_SETTINGS", 1));
        permissions.add(new PermissionListBean("WRITE_SETTINGS", 0.75));
        permissions.add(new PermissionListBean("WRITE_SYNC_SETTINGS", 0.25));
        permissions.add(new PermissionListBean("WRITE_VOICEMAIL", 1));
        return permissions;
    }

}
